name: Pruebas Git

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Change permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build app
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test